#=================================================================================
#==========================   spring设置  =========================================
#=================================================================================

spring:
  profiles:
    active:
      - @spring.active@
  task:
    scheduling:
      pool:
        size: 10 #定时任务线程池大小设置默认1设置为5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss #jackson时间格式化类
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss #日期格式化
  servlet:
    multipart:
      max-request-size: 5MB
      file-size-threshold: 0 #文件写入磁盘的阈值,设置为0，即上传就存储在服务器,如果是100则表示小于100会存储在内存
      max-file-size: 5MB    #单个文件上传的最大值
server:
  port: 8080

#===========================================================================
#==========================mybatis配置=======================================
#============================================================================

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #全局主键使用雪花算法生成id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql
  mapper-locations: "classpath:**/mapping/*.xml"

#=============================================================================
#======================== 自定义配置  =========================================
#=============================================================================
authorization:
  exclude:
    - /**/doc.html
    - /**/*.css
    - /**/*.js
    - /**/*.png
    - /**/*.jpg
    - /**/*.ico
    - /**/v3/**
    - /**/doLogin
    - /**/doRegister
    - /**/file/doDownload/**
    - /chat/**
  token-name: auth

# 图床服务
file:
  upload:
    url: xxxx
  download:
    url: xxxx
  signature: xxxx
  cipher-text: xxxx