#=================================================================================
#==========================   spring设置  =========================================
#=================================================================================

spring:
  profiles:
    active:
      - @spring.active@
  task:
    scheduling:
      pool:
        #定时任务线程池大小设置默认1设置为5
        size: 10
  jackson:
    time-zone: GMT+8
    #jackson时间格式化格式
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      #日期格式化
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-request-size: 30MB
      #文件写入磁盘的阈值,设置为0，即上传就存储在服务器,如果是100则表示小于100会存储在内存
      file-size-threshold: 0
      #单个文件上传的最大值
      max-file-size: 30MB
server:
  port: 8080

#===========================================================================
#==========================mybatis配置=======================================
#============================================================================

mybatis-plus:
  global-config:
    db-config:
      #全局主键使用雪花算法生成id
      id-type: assign_id
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: "classpath:**/mapping/*.xml"
#=============================================================================
#======================== swagger 配置  =======================================
#=============================================================================

springdoc:
  api-docs:
    #是否开启文档功能关系到swagger-ui能否开启
    enabled: true
    #swagger后端请求地址，查看swagger所有配置，同时也是配置web端的接口配置,必须写
    path: /v3/api-docs
  swagger-ui:
    #标签排序
    tags-sorter: alpha
    #操作排序
    operations-sorter: alpha
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger会自动重定向到swagger页面注意是path不是url
    path: /swagger
  group-configs:
    - group: 测试API
      packages-to-scan:
        - com.chat.controller
        - com.chat.domain

# knife4j的增强配置，不需要增强可以不配
knife4j:
  #开启访问默认路径doc.html
  enable: true
  setting:
    language: zh_cn
    #不开启缓存请求
    enable-request-cache: false
  #跨域请求
  cors: true
  #是否是生产环境，如果设置true,doc.html就不能访问
  production: @knife4j.enable@

#=============================================================================
#======================== 自定义配置  =========================================
#=============================================================================
authorization:
  exclude:
    - /**/doc.html
    - /**/*.css
    - /**/*.js
    - /**/*.png
    - /**/*.jpg
    - /**/*.ico
    - /**/v3/**
    - /**/doLogin
    - /**/doRegister
    - /**/file/doDownload/**
    - /chat/**
  token-name: auth

# 图床服务
file:
  upload:
    url: mpw:PNvTUoVSkYdCAlKWGfte6BZTn6F9HASyrPU2nLDesVdm2Y4MwdbUn0V0SeE5twgS
  download:
    url: mpw:PNvTUoVSkYdCAlKWGfte6BZTn6F9HASyrPU2nLDesVeZgdn3FUF0SLg4kkMlIwN6
  signature: ChatHub
  cipher-text: mpw:sjiNUIhHA9deLkoqF/ZKoIGePpQ6Cz2f2aJXJIQF3uygKrcdvyg1xOQtv66BKIQr

#日志文件存储位置
log:
  path: @log.path@