# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: chathub的部署与运行

#推送事件触发
on:
  push:
    branches:
    - main
    
jobs:
  chat-hub-build:
    name: chathub构建
    # 选择系统运行
    runs-on: ubuntu-latest
    #步骤运行命令
    steps:
      - name: 拉取仓库 # -name让github知道这个步骤的名字
        # 必须使用这个命令才行
        uses: actions/checkout@v4

      - name: 下载JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'opnejdk' # 发布版本
          java-version: '17'
      
      # - name: maven构建Jar包并运行
      #   run:  |
      #     apt-fast install tree
      #     cd ${{github.workspace}}
      #     tree -L 3 ./
      #     mvn -B package -DskipTests --file ./back-end/pom.xml
      #     tree -L 3 ./
      
      - name: 执行命令
        run: java -version    
          