# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: chathub的部署于运行

#什么事件触发
on:
  push:
    branches:
    - main
    
jobs:
  backend-build:
    name: 后端模块构建
    # 选择系统运行
    runs-on: ubuntu-latest
    #步骤运行命令
    steps:
      - name: 拉取仓库 # -name相当于一种注释
        # 必须使用这个命令才行
        uses: actions/checkout@v4

      - name: 创建工作区域
        run:  apt-fast update && apt-fast install tree &&  tree /home/runner/work/chat-hub/chat-hub && mkdir /home/github/server/chathub/backend & cd /home/github/server/chathub/backend  & pwd 

      - name: 下载JDK 17 并设置环境变量
        run: rm -f /tmp/apt-fast.lock && apt-fast update && apt-fast install openjdk-17-jdk && java -version
