name: chathub的部署与运行

# 触发事件
on:
  push:
    branches:
      - main

jobs:
  backend-build:
    name: 后端模块构建
    # 选择系统运行
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # 步骤运行命令
    steps:
      - name: 拉取仓库 # -name相当于一种注释
        uses: actions/checkout@v4

      - name: 下载JDK 17 并设置环境变量
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: 创建工作目录
        run: mkdir -p ${{ github.workspace }}/server/chathub/backend

      - name: 创建文件
        run: echo "Hello, World!" > ${{ github.workspace }}/server/chathub/backend/hello.txt

      - name: 安装 tree 工具并显示目录结构
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
