# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: chathub的部署于运行

#什么事件触发
on:
  push:
    branches:
    - main
    
jobs:
  repobuild:
    users: actions/checkout@v4
  #构建java
  javabuild:
    #选择系统运行
    runs-on: ubuntu-latest
    #步骤运行命令
    steps:
      #运行的命令
      - run: mvn -version
      - run: node --version
      - run: java -version
    